# Generated by Django 5.1.2 on 2024-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('highlights', models.TextField()),
                ('spaces', models.TextField()),
                ('amenities', models.JSONField()),
                ('meals', models.TextField()),
                ('location_details', models.TextField()),
                ('experiences', models.TextField()),
                ('faqs', models.JSONField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
            ],
        ),
    ]
